sonar.projectKey=becas-universitarias
sonar.projectName=Sistema de Gestion de Becas Universitarias
sonar.sources=apps,config
sonar.exclusions=**/migrations/**,**/tests/**
sonar.tests=apps
sonar.test.inclusions=**/tests/**
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8
