# Generated by Django 5.2.15 on 2026-06-15 22:42

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("configuracion", "0001_initial"),
        ("convocatorias", "0002_registrar_tarea_beat"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalPostulacion",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("BORRADOR", "Borrador"),
                            ("ENVIADA", "Enviada"),
                            ("EN_REVISION", "En Revisión"),
                            ("APROBADA", "Aprobada"),
                            ("PROCESADA", "Procesada"),
                            ("ADJUDICADA", "Adjudicada"),
                            ("NO_ADJUDICADA", "No Adjudicada"),
                            ("LISTA_ESPERA", "Lista de Espera"),
                            ("RECHAZADA_NO_PRESENTACION", "Rechazada - No Presentación"),
                            ("RECHAZADA_IDENTIDAD", "Rechazada - Identidad"),
                            ("RECHAZADA_DOCUMENTACION", "Rechazada - Documentación"),
                        ],
                        default="BORRADOR",
                        max_length=30,
                        verbose_name="estado",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "fecha_envio",
                    models.DateTimeField(blank=True, null=True, verbose_name="fecha de envío"),
                ),
                (
                    "observaciones_identidad",
                    models.TextField(blank=True, verbose_name="observaciones de identidad"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "beca",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="convocatorias.beca",
                        verbose_name="beca",
                    ),
                ),
                (
                    "convocatoria",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="convocatorias.convocatoria",
                        verbose_name="convocatoria",
                    ),
                ),
                (
                    "estudiante",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="estudiante",
                    ),
                ),
                (
                    "formulario",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="configuracion.formulariosocioeconomico",
                        verbose_name="formulario socioeconómico",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical postulación",
                "verbose_name_plural": "historical postulaciones",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Postulacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("BORRADOR", "Borrador"),
                            ("ENVIADA", "Enviada"),
                            ("EN_REVISION", "En Revisión"),
                            ("APROBADA", "Aprobada"),
                            ("PROCESADA", "Procesada"),
                            ("ADJUDICADA", "Adjudicada"),
                            ("NO_ADJUDICADA", "No Adjudicada"),
                            ("LISTA_ESPERA", "Lista de Espera"),
                            ("RECHAZADA_NO_PRESENTACION", "Rechazada - No Presentación"),
                            ("RECHAZADA_IDENTIDAD", "Rechazada - Identidad"),
                            ("RECHAZADA_DOCUMENTACION", "Rechazada - Documentación"),
                        ],
                        default="BORRADOR",
                        max_length=30,
                        verbose_name="estado",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(auto_now_add=True, verbose_name="fecha de creación"),
                ),
                (
                    "fecha_envio",
                    models.DateTimeField(blank=True, null=True, verbose_name="fecha de envío"),
                ),
                (
                    "observaciones_identidad",
                    models.TextField(blank=True, verbose_name="observaciones de identidad"),
                ),
                (
                    "beca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="postulaciones",
                        to="convocatorias.beca",
                        verbose_name="beca",
                    ),
                ),
                (
                    "convocatoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="postulaciones",
                        to="convocatorias.convocatoria",
                        verbose_name="convocatoria",
                    ),
                ),
                (
                    "estudiante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="postulaciones",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="estudiante",
                    ),
                ),
                (
                    "formulario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="postulaciones",
                        to="configuracion.formulariosocioeconomico",
                        verbose_name="formulario socioeconómico",
                    ),
                ),
            ],
            options={
                "verbose_name": "postulación",
                "verbose_name_plural": "postulaciones",
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="DocumentoPostulacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "validado",
                    models.BooleanField(
                        blank=True,
                        help_text="None=pendiente, True=aprobado, False=rechazado",
                        null=True,
                        verbose_name="validado",
                    ),
                ),
                (
                    "archivo",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="documentos/",
                        verbose_name="archivo digitalizado",
                    ),
                ),
                (
                    "fecha_validacion",
                    models.DateTimeField(blank=True, null=True, verbose_name="fecha de validación"),
                ),
                (
                    "tipo_documento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documentos_postulacion",
                        to="convocatorias.tipodocumento",
                        verbose_name="tipo de documento",
                    ),
                ),
                (
                    "postulacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="postulaciones.postulacion",
                        verbose_name="postulación",
                    ),
                ),
            ],
            options={
                "verbose_name": "documento de postulación",
                "verbose_name_plural": "documentos de postulación",
                "unique_together": {("postulacion", "tipo_documento")},
            },
        ),
    ]
