# Generated by Django 5.2.15 on 2026-06-15 22:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("postulaciones", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpostulacion",
            name="puntaje_socioeconomico",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="puntaje socioeconómico",
            ),
        ),
        migrations.AddField(
            model_name="postulacion",
            name="puntaje_socioeconomico",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="puntaje socioeconómico",
            ),
        ),
    ]
