# Generated by Django 5.2.15 on 2026-06-17 03:13

from django.db import migrations, models


def sembrar_contador_inicial(apps, schema_editor):
    ContadorReferencia = apps.get_model("postulaciones", "ContadorReferencia")
    ContadorReferencia.objects.get_or_create(pk=1, defaults={"ultimo_numero": 0})


class Migration(migrations.Migration):
    dependencies = [
        ("postulaciones", "0002_historicalpostulacion_puntaje_socioeconomico_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContadorReferencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "ultimo_numero",
                    models.PositiveIntegerField(default=0, verbose_name="último número emitido"),
                ),
            ],
            options={
                "verbose_name": "contador de referencia",
                "verbose_name_plural": "contador de referencia",
            },
        ),
        migrations.AddField(
            model_name="historicalpostulacion",
            name="numero_referencia",
            field=models.PositiveIntegerField(
                blank=True,
                db_index=True,
                help_text="Asignado al enviar la postulación; identifica la constancia impresa.",
                null=True,
                verbose_name="número de referencia",
            ),
        ),
        migrations.AddField(
            model_name="postulacion",
            name="numero_referencia",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Asignado al enviar la postulación; identifica la constancia impresa.",
                null=True,
                unique=True,
                verbose_name="número de referencia",
            ),
        ),
        migrations.RunPython(sembrar_contador_inicial, migrations.RunPython.noop),
    ]
