# Generated by Django 5.2.15 on 2026-06-17 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("configuracion", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="formulariosocioeconomico",
            name="banos",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="baños"),
        ),
        migrations.AddField(
            model_name="formulariosocioeconomico",
            name="cantidad_hijos",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="cantidad de hijos"
            ),
        ),
        migrations.AddField(
            model_name="formulariosocioeconomico",
            name="comedores",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="comedores"),
        ),
        migrations.AddField(
            model_name="formulariosocioeconomico",
            name="dependencia_economica",
            field=models.CharField(
                blank=True,
                choices=[
                    ("INDEPENDIENTE", "Independiente"),
                    ("PADRE_MADRE", "Solo de padre o madre"),
                    ("OTRO_FAMILIAR", "Otro familiar"),
                    ("PAREJA", "De la pareja"),
                    ("AMBOS_PADRES", "Ambos padres"),
                ],
                max_length=20,
                verbose_name="¿de quién depende usted?",
            ),
        ),
        migrations.AddField(
            model_name="formulariosocioeconomico",
            name="detalle_discapacidad",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="tipo y grado de discapacidad"
            ),
        ),
        migrations.AddField(
            model_name="formulariosocioeconomico",
            name="detalle_otro_beneficio",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="¿cuál otro beneficio?"
            ),
        ),
        migrations.AddField(
            model_name="formulariosocioeconomico",
            name="dormitorios",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="dormitorios"),
        ),
        migrations.AddField(
            model_name="formulariosocioeconomico",
            name="lugar_procedencia",
            field=models.CharField(
                blank=True,
                help_text="Solo si su procedencia es otra ciudad o provincia.",
                max_length=150,
                verbose_name="lugar de procedencia",
            ),
        ),
        migrations.AddField(
            model_name="formulariosocioeconomico",
            name="numero_celular",
            field=models.CharField(blank=True, max_length=20, verbose_name="número de celular"),
        ),
        migrations.AddField(
            model_name="formulariosocioeconomico",
            name="patios",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="patios"),
        ),
        migrations.AddField(
            model_name="formulariosocioeconomico",
            name="residencia_barrio",
            field=models.CharField(blank=True, max_length=100, verbose_name="barrio"),
        ),
        migrations.AddField(
            model_name="formulariosocioeconomico",
            name="residencia_calle",
            field=models.CharField(blank=True, max_length=150, verbose_name="calle"),
        ),
        migrations.AddField(
            model_name="formulariosocioeconomico",
            name="residencia_lugar",
            field=models.CharField(blank=True, max_length=150, verbose_name="lugar de residencia"),
        ),
        migrations.AddField(
            model_name="formulariosocioeconomico",
            name="residencia_provincia",
            field=models.CharField(blank=True, max_length=100, verbose_name="provincia"),
        ),
        migrations.AddField(
            model_name="formulariosocioeconomico",
            name="residencia_zona_anillo",
            field=models.CharField(blank=True, max_length=100, verbose_name="zona o anillo"),
        ),
        migrations.AddField(
            model_name="formulariosocioeconomico",
            name="salas",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="salas"),
        ),
        migrations.AddField(
            model_name="formulariosocioeconomico",
            name="telefono_referencia",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="teléfono de referencia"
            ),
        ),
        migrations.AddField(
            model_name="formulariosocioeconomico",
            name="tiene_discapacidad",
            field=models.BooleanField(
                default=False, verbose_name="¿tiene algún tipo de discapacidad?"
            ),
        ),
        migrations.AddField(
            model_name="formulariosocioeconomico",
            name="tiene_hijos",
            field=models.BooleanField(default=False, verbose_name="¿tiene hijos?"),
        ),
        migrations.AddField(
            model_name="formulariosocioeconomico",
            name="tipo_ocupacion_sosten",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ASALARIADO_FORMAL", "Asalariado formal"),
                    ("ASALARIADO_INFORMAL", "Asalariado informal"),
                    ("COMERCIANTE_MAYORISTA", "Comerciante mayorista"),
                    ("RENTISTA", "Rentista"),
                    ("COMERCIANTE_MINORISTA", "Comerciante minorista"),
                    ("AGRICULTOR", "Agricultor"),
                ],
                max_length=25,
                verbose_name="ocupación de quien lo sostiene económicamente",
            ),
        ),
        migrations.AddField(
            model_name="formulariosocioeconomico",
            name="tipo_tenencia_vivienda",
            field=models.CharField(
                blank=True,
                choices=[
                    ("HERENCIA", "Herencia"),
                    ("DE_LOS_PADRES", "De los padres"),
                    ("CEDIDA", "Cedida"),
                    ("ANTICRETICO", "Anticrético"),
                    ("ALQUILER", "Alquiler"),
                ],
                max_length=20,
                verbose_name="tenencia de la vivienda",
            ),
        ),
        migrations.CreateModel(
            name="IntegranteFamiliar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "nombre_completo",
                    models.CharField(max_length=200, verbose_name="nombre completo"),
                ),
                ("parentesco", models.CharField(max_length=50, verbose_name="parentesco")),
                ("edad", models.PositiveSmallIntegerField(verbose_name="edad")),
                (
                    "ocupacion",
                    models.CharField(blank=True, max_length=100, verbose_name="ocupación"),
                ),
                (
                    "observacion",
                    models.CharField(blank=True, max_length=200, verbose_name="observación"),
                ),
                (
                    "formulario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integrantes_familiares",
                        to="configuracion.formulariosocioeconomico",
                        verbose_name="formulario socioeconómico",
                    ),
                ),
            ],
            options={
                "verbose_name": "integrante familiar",
                "verbose_name_plural": "integrantes familiares",
            },
        ),
    ]
