# Generated by Django 5.2.15 on 2026-06-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0002_formulario_campos_dubs002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrantefamiliar',
            name='parentesco',
            field=models.CharField(choices=[('PADRE', 'Padre'), ('MADRE', 'Madre'), ('HERMANO', 'Hermano'), ('HERMANA', 'Hermana'), ('HIJO', 'Hijo/a'), ('ABUELO', 'Abuelo/a'), ('TIO', 'Tío/a'), ('PRIMO', 'Primo/a'), ('OTRO', 'Otro')], max_length=20, verbose_name='parentesco'),
        ),
    ]
