# Generated by Django 5.2.15 on 2026-06-27 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0004_refactor_scoring_system'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rangoingreso',
            options={'ordering': ['monto_minimo'], 'verbose_name': 'rango de ingreso familiar', 'verbose_name_plural': 'rangos de ingreso familiar'},
        ),
        migrations.AlterField(
            model_name='opciondependencia',
            name='nombre',
            field=models.CharField(max_length=150, unique=True, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='opciondependencia',
            name='valor_puntaje',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='valor de puntaje'),
        ),
        migrations.AlterField(
            model_name='opciondiscapacidad',
            name='nombre',
            field=models.CharField(max_length=150, unique=True, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='opciondiscapacidad',
            name='valor_puntaje',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='valor de puntaje'),
        ),
        migrations.AlterField(
            model_name='opcionotrobeneficio',
            name='nombre',
            field=models.CharField(max_length=150, unique=True, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='opcionotrobeneficio',
            name='valor_puntaje',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='valor de puntaje'),
        ),
        migrations.AlterField(
            model_name='rangogrupofamiliar',
            name='cantidad_maxima',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Dejar vacío para indicar 'sin límite superior'.", null=True, verbose_name='cantidad máxima'),
        ),
        migrations.AlterField(
            model_name='rangogrupofamiliar',
            name='cantidad_minima',
            field=models.PositiveSmallIntegerField(verbose_name='cantidad mínima'),
        ),
        migrations.AlterField(
            model_name='rangogrupofamiliar',
            name='nombre',
            field=models.CharField(max_length=150, unique=True, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='rangogrupofamiliar',
            name='valor_puntaje',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='valor de puntaje'),
        ),
        migrations.AlterField(
            model_name='rangoinfraestructura',
            name='nombre',
            field=models.CharField(max_length=150, unique=True, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='rangoinfraestructura',
            name='total_maximo',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Dejar vacío para indicar 'sin límite superior'.", null=True, verbose_name='total máximo de ambientes'),
        ),
        migrations.AlterField(
            model_name='rangoinfraestructura',
            name='total_minimo',
            field=models.PositiveSmallIntegerField(verbose_name='total mínimo de ambientes'),
        ),
        migrations.AlterField(
            model_name='rangoinfraestructura',
            name='valor_puntaje',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='valor de puntaje'),
        ),
        migrations.AlterField(
            model_name='rangoingreso',
            name='monto_maximo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Dejar vacío para indicar 'sin límite superior'.", max_digits=12, null=True, verbose_name='monto máximo (Bs.)'),
        ),
        migrations.AlterField(
            model_name='rangoingreso',
            name='monto_minimo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Dejar vacío para indicar 'sin límite inferior'.", max_digits=12, null=True, verbose_name='monto mínimo (Bs.)'),
        ),
        migrations.AlterField(
            model_name='rangoingreso',
            name='nombre',
            field=models.CharField(max_length=150, unique=True, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='rangoingreso',
            name='valor_puntaje',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='valor de puntaje'),
        ),
        migrations.AlterField(
            model_name='tipoocupacionsosten',
            name='documento_adjuntar',
            field=models.CharField(blank=True, help_text='Documento recomendado para acreditar esta ocupación.', max_length=200, verbose_name='documento a adjuntar'),
        ),
        migrations.AlterField(
            model_name='tipoocupacionsosten',
            name='nombre',
            field=models.CharField(max_length=150, unique=True, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='tipoocupacionsosten',
            name='valor_puntaje',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='valor de puntaje'),
        ),
        migrations.AlterField(
            model_name='tipotenenciavivienda',
            name='documento_adjuntar',
            field=models.CharField(blank=True, help_text='Documento recomendado para acreditar este tipo de tenencia.', max_length=200, verbose_name='documento a adjuntar'),
        ),
        migrations.AlterField(
            model_name='tipotenenciavivienda',
            name='nombre',
            field=models.CharField(max_length=150, unique=True, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='tipotenenciavivienda',
            name='valor_puntaje',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='valor de puntaje'),
        ),
    ]
