# Generated by Django 5.2.15 on 2026-06-19 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("convocatorias", "0003_datos_convocatorias_becas"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ResumenIA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "prompt_adicional",
                    models.TextField(blank=True, verbose_name="instrucción adicional"),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("PROCESANDO", "Procesando"),
                            ("COMPLETADO", "Completado"),
                            ("ERROR", "Error"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                        verbose_name="estado",
                    ),
                ),
                ("resultado", models.TextField(blank=True, verbose_name="resultado")),
                ("error_detalle", models.TextField(blank=True, verbose_name="detalle del error")),
                (
                    "fecha_creacion",
                    models.DateTimeField(auto_now_add=True, verbose_name="fecha de creación"),
                ),
                (
                    "fecha_completado",
                    models.DateTimeField(blank=True, null=True, verbose_name="fecha de completado"),
                ),
                (
                    "convocatoria",
                    models.ForeignKey(
                        blank=True,
                        help_text="Vacío = resumen agregado de todas las convocatorias.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resumenes_ia",
                        to="convocatorias.convocatoria",
                        verbose_name="convocatoria",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resumenes_ia",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="solicitado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "resumen con IA",
                "verbose_name_plural": "resúmenes con IA",
                "ordering": ["-fecha_creacion"],
            },
        ),
    ]
