# Generated by Django 5.2.15 on 2026-06-19 22:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reportes", "0002_registrar_tarea_beat"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("titulo", models.CharField(blank=True, max_length=200, verbose_name="título")),
                (
                    "fecha_creacion",
                    models.DateTimeField(auto_now_add=True, verbose_name="fecha de creación"),
                ),
                (
                    "fecha_actualizacion",
                    models.DateTimeField(auto_now=True, verbose_name="última actualización"),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversaciones_ia",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "conversación con IA",
                "verbose_name_plural": "conversaciones con IA",
                "ordering": ["-fecha_actualizacion"],
            },
        ),
        migrations.CreateModel(
            name="MensajeChat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "rol",
                    models.CharField(
                        choices=[
                            ("USUARIO", "Usuario"),
                            ("ASISTENTE", "Asistente"),
                            ("SISTEMA", "Sistema"),
                        ],
                        max_length=20,
                        verbose_name="rol",
                    ),
                ),
                ("contenido", models.TextField(verbose_name="contenido")),
                (
                    "tools_usadas",
                    models.JSONField(blank=True, null=True, verbose_name="tools usadas"),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(auto_now_add=True, verbose_name="fecha de creación"),
                ),
                (
                    "conversacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mensajes",
                        to="reportes.conversacion",
                        verbose_name="conversación",
                    ),
                ),
            ],
            options={
                "verbose_name": "mensaje de chat",
                "verbose_name_plural": "mensajes de chat",
                "ordering": ["fecha_creacion"],
            },
        ),
    ]
