# Generated by Django 5.2.15 on 2026-06-19 23:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reportes", "0004_registrar_tarea_beat_chat"),
    ]

    operations = [
        migrations.AddField(
            model_name="mensajechat",
            name="archivo",
            field=models.FileField(
                blank=True, null=True, upload_to="chat_ia/%Y/%m/", verbose_name="archivo adjunto"
            ),
        ),
    ]
