# Generated by Django 5.2.15 on 2026-06-15 21:34

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Beca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nombre", models.CharField(max_length=150, unique=True, verbose_name="nombre")),
                ("descripcion", models.TextField(blank=True, verbose_name="descripción")),
                ("activa", models.BooleanField(default=True, verbose_name="activa")),
            ],
            options={
                "verbose_name": "beca",
                "verbose_name_plural": "becas",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="TipoDocumento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nombre", models.CharField(max_length=150, unique=True, verbose_name="nombre")),
                ("descripcion", models.TextField(blank=True, verbose_name="descripción")),
                ("activo", models.BooleanField(default=True, verbose_name="activo")),
            ],
            options={
                "verbose_name": "tipo de documento",
                "verbose_name_plural": "tipos de documento",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalConvocatoria",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("nombre", models.CharField(max_length=200, verbose_name="nombre")),
                ("descripcion", models.TextField(blank=True, verbose_name="descripción")),
                ("fecha_apertura", models.DateTimeField(verbose_name="fecha de apertura")),
                ("fecha_cierre", models.DateTimeField(verbose_name="fecha de cierre")),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("BORRADOR", "Borrador"),
                            ("PUBLICADA", "Publicada"),
                            ("CERRADA", "Cerrada"),
                        ],
                        default="BORRADOR",
                        max_length=20,
                        verbose_name="estado",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "creada_por",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creada por",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical convocatoria",
                "verbose_name_plural": "historical convocatorias",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Convocatoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nombre", models.CharField(max_length=200, verbose_name="nombre")),
                ("descripcion", models.TextField(blank=True, verbose_name="descripción")),
                ("fecha_apertura", models.DateTimeField(verbose_name="fecha de apertura")),
                ("fecha_cierre", models.DateTimeField(verbose_name="fecha de cierre")),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("BORRADOR", "Borrador"),
                            ("PUBLICADA", "Publicada"),
                            ("CERRADA", "Cerrada"),
                        ],
                        default="BORRADOR",
                        max_length=20,
                        verbose_name="estado",
                    ),
                ),
                (
                    "becas",
                    models.ManyToManyField(
                        blank=True, to="convocatorias.beca", verbose_name="becas disponibles"
                    ),
                ),
                (
                    "creada_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="convocatorias_creadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creada por",
                    ),
                ),
                (
                    "documentos_requeridos",
                    models.ManyToManyField(
                        blank=True,
                        to="convocatorias.tipodocumento",
                        verbose_name="documentos requeridos",
                    ),
                ),
            ],
            options={
                "verbose_name": "convocatoria",
                "verbose_name_plural": "convocatorias",
                "ordering": ["-fecha_apertura"],
            },
        ),
    ]
