# Generated by Django 5.2.15 on 2026-06-20 00:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("convocatorias", "0003_datos_convocatorias_becas"),
    ]

    operations = [
        migrations.AddField(
            model_name="beca",
            name="peso_dependencia_economica",
            field=models.PositiveSmallIntegerField(
                default=30, verbose_name="peso: dependencia económica (%)"
            ),
        ),
        migrations.AddField(
            model_name="beca",
            name="peso_grupo_familiar",
            field=models.PositiveSmallIntegerField(
                default=20, verbose_name="peso: grupo familiar (%)"
            ),
        ),
        migrations.AddField(
            model_name="beca",
            name="peso_procedencia",
            field=models.PositiveSmallIntegerField(
                default=5, verbose_name="peso: procedencia (%)"
            ),
        ),
        migrations.AddField(
            model_name="beca",
            name="peso_tenencia_vivienda",
            field=models.PositiveSmallIntegerField(
                default=15, verbose_name="peso: tenencia de vivienda (%)"
            ),
        ),
        migrations.AddField(
            model_name="beca",
            name="peso_infraestructura",
            field=models.PositiveSmallIntegerField(
                default=15, verbose_name="peso: infraestructura (%)"
            ),
        ),
        migrations.AddField(
            model_name="beca",
            name="peso_otro_beneficio",
            field=models.PositiveSmallIntegerField(
                default=10, verbose_name="peso: otro beneficio (%)"
            ),
        ),
        migrations.AddField(
            model_name="beca",
            name="peso_discapacidad",
            field=models.PositiveSmallIntegerField(
                default=5, verbose_name="peso: discapacidad (%)"
            ),
        ),
    ]
