# Generated by Django 5.2.15 on 2026-06-20 00:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("convocatorias", "0003_datos_convocatorias_becas"),
    ]

    operations = [
        migrations.AddField(
            model_name="beca",
            name="peso_desempleo",
            field=models.PositiveSmallIntegerField(default=20, verbose_name="peso: desempleo (%)"),
        ),
        migrations.AddField(
            model_name="beca",
            name="peso_familiares",
            field=models.PositiveSmallIntegerField(
                default=20, verbose_name="peso: cantidad de familiares (%)"
            ),
        ),
        migrations.AddField(
            model_name="beca",
            name="peso_ingreso",
            field=models.PositiveSmallIntegerField(
                default=40, verbose_name="peso: ingreso familiar (%)"
            ),
        ),
        migrations.AddField(
            model_name="beca",
            name="peso_no_propietario",
            field=models.PositiveSmallIntegerField(
                default=10, verbose_name="peso: no propietario de vivienda (%)"
            ),
        ),
        migrations.AddField(
            model_name="beca",
            name="peso_sin_beca_previa",
            field=models.PositiveSmallIntegerField(
                default=10, verbose_name="peso: sin beca previa (%)"
            ),
        ),
    ]
