# Generated by Django 5.2.15 on 2026-06-15 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("acceso", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PerfilEstudiante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("legajo", models.CharField(max_length=20, unique=True, verbose_name="legajo")),
                ("carrera", models.CharField(max_length=150, verbose_name="carrera")),
                ("anio_ingreso", models.PositiveSmallIntegerField(verbose_name="año de ingreso")),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil_estudiante",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "perfil de estudiante",
                "verbose_name_plural": "perfiles de estudiante",
            },
        ),
    ]
