# Generated by Django 5.2.15 on 2026-06-15 19:46

from django.db import migrations

GRUPOS = ["Director", "Operador", "Estudiante"]


def crear_grupos(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    for nombre in GRUPOS:
        Group.objects.get_or_create(name=nombre)


def eliminar_grupos(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(name__in=GRUPOS).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("acceso", "0002_perfilestudiante"),
    ]

    operations = [
        migrations.RunPython(crear_grupos, eliminar_grupos),
    ]
